### PR TITLE
chore(data files): create endpoint class to download method & add tqdm

### LINKED ISSUE #133: Download SIA (Produção Ambulatorial) data besides São Paulo
I'm trying download data SIA (Produção Ambulatorial) of other states, like RJ, BA, etc, but, I'm having this problem:
Code:
pa = download('RJ',2020,12,group='PA')[0]
pa = parquets_to_dataframe(pa)
pa.head()
Error:
AttributeError: 'NoneType' object has no attribute 'head'

image

### LINKED ISSUE #147: Only initialize FTP on demand
Currently, FTP is being initialized when the SINAN module is imported.

Ideally, it should be initialized only when needed for a Download.

### LINKED ISSUE #148: Add get_available_years for SIM
This function should in fact be available for all datasets

### LINKED ISSUE #157: Remove "readdbc" Module from Utilities
The "readdbc" module in the "utilities" package in the PySUS project (located at [PySUS readdbc.py](https://github.com/AlertaDengue/PySUS/blob/main/pysus/utilities/readdbc.py)) has recently been moved to a separate package called "pyreaddbc" (https://github.com/osl-incubator/pyreaddbc).

Proposed Steps for the complete migration:

1. Remove the "readdbc" module from the PySUS project and add it as a dependency.
2. Update the README of pyreaddbc to include the credits to AlertaDengue properly.
3. Notify the community about this change and encourage them to contribute to "pyreaddbc."

By following these steps, we can maintain a cleaner and more focused codebase in the PySUS
project while ensuring that the "pyreaddbc" package could help more projects in the open source
software community.

If is it ok, we can start to move this forward as soon as possible.

### LINKED ISSUE #158: [Modularization] Create a class to hold the result of a FTP Download
The file must contain functionalities to:
- Parse to DBF
- Parse to Parquets
- to_dataframe()

### LINKED ISSUE #159: [Docs] Fix commented code on documentation/notebooks
depends on #158

### PR DESCRIPTION
**Pull request by luabida**
fix #157 
fix #158 
fix #159 
fix #148
fix #147 
fix #133

### CODE REVIEW

**Comment by luabida** [comment]
image

**Comment by luabida** [comment]
@fccoelho can be merged and released when CI is green

**Review by fccoelho — APPROVED** [review]
I may be worth adding to the release notes a guide to upgrading from the old API to the new. This release will break existing user code.

**Comment by luabida** [comment]
@fccoelho I'll add it when the release is generated, last time I've checked, the release was failing quietly and wasn't generating any release at all.. I've commented it with sandro last week to see what's going on

**Pull request merged**
