### PR TITLE
bugfix(test-data): remove left data from test and python gitignore template

### PR DESCRIPTION
**Pull request by luabida**
Data from testes were left into the repo. 

@fccoelho there is also a `.idea` dir, is it necessary?

### CODE REVIEW

**Comment by fccoelho** [comment]
> @fccoelho there is also a `.idea` dir, is it necessary?

It should be on `.gitignore` too, it contains the pycharm IDE configuration files

**Review by fccoelho — CHANGES_REQUESTED** [review]
I think that we should add *.csv* and *.parquet to gitignore

**Review by fccoelho — APPROVED** [review]

**Comment by esloch** [comment]
@luabida, I think  that files necessary for the execution of the tests were [removed](https://github.com/AlertaDengue/PySUS/pull/110/checks#step:7:82).
```
pysus/tests/test_data/EPR-2016-06-01-2016.dbf
pysus/tests/test_data/chik.pickle
pysus/tests/test_data/sids.dbc
```

**Comment by luabida** [comment]
@esloch yes, the tests are gonna need refactor to create these files at execution. I've opened an issue to this #111

**Pull request merged**
